### ISSUE TITLE
AttributeError: File was not opened in read mode.

### ISSUE THREAD

**Issue by seanastrakhan-gp** [uktrade/s3chunkuploader#11]
I'm getting the following issue:
 File "/Users/sean/.local/share/virtualenvs/Resource-service-FPzlV6mx/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 113, in read
    raise AttributeError("File was not opened in read mode.")

Here's my settings.py:

> CHUNK_UPLOADER_AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY')
> CHUNK_UPLOADER_AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_KEY')
> CHUNK_UPLOADER_AWS_AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
> CHUNK_UPLOADER_S3_APPEND_DATETIME_ON_UPLOAD	= True
> FILE_UPLOAD_HANDLERS = ('s3chunkuploader.file_handler.S3FileUploadHandler',)

Here's my Model:
```
class Resources(BaseModel):
    resource_url = models.FileField(storage=storages.SecureMediaStorage(),
                                    upload_to=resources_url_upload_to,
                                    blank=True,
                                    null=True)
    resource_url_local = models.FileField(
                                upload_to=resources_url_upload_to,
                                blank=True,
                                null=True)
```

I get the issue whether I populate the _resource_url_ or the _resource_url_local_

Here's how it gets populated in the Serializer:
```
    def create(self, validated_data):
          resource = models.Resources(**validated_data)
```

**Comment by seanastrakhan-gp** [comment]
Disregard - I realized it wasn't working with models using S3Boto3Storage

**Comment by akarshan96** [comment]
@seanastrakhan-gp @harel I am facing the same issue. How to make it work with FileField? 
I have changed the file._mode to 'rb' for serializer to read the S3Boto3StorageFile but on .save() it's re uploading the file to DEFAULT_STORAGE. Even tried with S3FileField. 

Another approach I used is to replace FileField with CharField and save s3 key.

Could you please guide me.

**Comment by seanastrakhan-gp** [comment]
@akarshan96 did you try remove this line in Settings.py?
`DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
`

**Comment by harel** [comment]
You don't really use a file field with this. Remember that there is no "local" file - it's a reference to the object stored on S3. 
Use instead the S3FileField from within the package:


`
from s3chunkuploader.fields import S3FileField

class MyMoel(models.Model):
    myfile = S3FileField(max_length=2000, null=True, blank=True)

`
